# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-20 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='status',
            field=models.CharField(choices=[(b'open', b'open'), (b'merged', b'merged'), (b'paid', b'paid')], default=b'open', max_length=250),
        ),
    ]
