# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-28 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20160720_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='language',
            field=models.CharField(blank=True, choices=[(b'C#', b'C#'), (b'C', b'C'), (b'C++', b'C++'), (b'CSS', b'CSS'), (b'Erlang', b'Erlang'), (b'Haskell', b'Haskell'), (b'HTML', b'HTML'), (b'Go', b'Go'), (b'Java', b'Java'), (b'JavaScript', b'JavaScript'), (b'NodeJS', b'NodeJS'), (b'Perl', b'Perl'), (b'PHP', b'PHP'), (b'Python', b'Python'), (b'Ruby', b'Ruby'), (b'Scala', b'Scala'), (b'Shell', b'Shell'), (b'VB', b'VB')], max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[(b'open', b'open'), (b'in review', b'in review'), (b'taken', b'taken'), (b'paid', b'paid'), (b'closed', b'closed')], default=b'open', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='payment_service',
            field=models.CharField(blank=True, choices=[(b'paypal', 'Paypal')], max_length=255, null=True),
        ),
    ]
