# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-30 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20170128_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='txn_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
